version: "3.2"

services:
  builder:
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./html
        target: /root/html
      - type: bind
        source: ./src
        target: /root/src   
    stdin_open: true
    tty: false


 #   volumes:
 #     - './src:/root/src'
 #     - './html:/root/html'

#  services:
#        client:
#            image: nginx
#            ports:
#                - 8000:80
#            volumes:
#                - ./src:/usr/share/nginx/html

#services:
#  janus-gatew:
#    image: linagora/docker-janus-gateway
#    ports:
#      - "80:80"
#      - "7088:7088"
#      - "8088:8088"
#      - "8188:8188"
#      - "8089:8089"
#      - "10000-10200:10000-10200/udp"
#    environment:
#      - DOCKER_IP=${DOCKER_IP}
